# Generated by Django 5.2 on 2025-05-09 05:42

import django.db.models.deletion
import image_cropping.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_alter_store_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание магазина'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название магазина'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('discount', models.PositiveIntegerField(verbose_name='Скидка в сомах')),
                ('on_products', models.ManyToManyField(blank=True, related_name='promo_codes_applicable', to='partner.product', verbose_name='Товары, на которые действует промокод')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='partner.store', verbose_name='Магазин')),
                ('used_by', models.ManyToManyField(blank=True, related_name='used_promo_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи, использовавшие промокод')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='StoreStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='store_stories/icons/', verbose_name='Иконка (1:1)')),
                ('icon_cropping', image_cropping.fields.ImageRatioField('icon', '600x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='icon cropping')),
                ('image', models.ImageField(upload_to='store_stories/full/', verbose_name='Изображение для экрана')),
                ('image_cropping', image_cropping.fields.ImageRatioField('image', '1080x1920', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='partner.store', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Сторис магазина',
                'verbose_name_plural': 'Сторисы магазинов',
            },
        ),
    ]
