# Generated by Django 5.2 on 2025-05-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_store_description_alter_store_name_promocode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='closing_time',
            field=models.TimeField(default='11:00', verbose_name='Время закрытия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='opening_time',
            field=models.TimeField(default='12:00', verbose_name='Время открытия'),
            preserve_default=False,
        ),
    ]
